# Generated by Django 2.1.1 on 2018-11-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ewsregistry',
            table='ews_registry',
        ),
        migrations.AlterModelTable(
            name='ewsrepository',
            table='ews_repository',
        ),
        migrations.AlterModelTable(
            name='ewsrepositorypub',
            table='ews_repository_pub',
        ),
    ]
