# Generated by Django 2.1.1 on 2018-11-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20181101_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewsrepository',
            name='repository_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
