# Generated by Django 2.1.1 on 2018-11-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20181101_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ewsrepository',
            name='tab_user',
        ),
    ]
