# Generated by Django 2.1.1 on 2019-01-22 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EwsFirewall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(blank=True, max_length=255, null=True)),
                ('cmd', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('firewall_json', models.CharField(blank=True, max_length=255, null=True)),
                ('tab_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'db_table': 'ews_firewall',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='EwsHostFirewall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('tab_firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.EwsFirewall')),
                ('tab_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.EwsHost')),
                ('tab_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ews_host_firewall',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='ewsfirewall',
            name='tab_host_firewall',
            field=models.ManyToManyField(through='hosts.EwsHostFirewall', to='hosts.EwsHost'),
        ),
        migrations.AddField(
            model_name='ewsfirewall',
            name='tab_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
