# Generated by Django 2.1.1 on 2019-01-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20190122_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ewsfirewall',
            old_name='cmd',
            new_name='policy_json',
        ),
        migrations.RenameField(
            model_name='ewsfirewall',
            old_name='firewall_json',
            new_name='policy_name',
        ),
        migrations.AddField(
            model_name='ewsfirewall',
            name='iscustomize',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ewshostfirewall',
            name='policy_cmd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ewshostfirewall',
            name='tab_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
