# Generated by Django 2.1.1 on 2019-12-12 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EwsCicd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cicd_user', models.CharField(blank=True, max_length=255, null=True)),
                ('cicd_passwd', models.CharField(blank=True, max_length=255, null=True)),
                ('cicd_token', models.CharField(blank=True, max_length=255, null=True)),
                ('cicd_url', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('tab_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ews_cicd',
                'ordering': ['-created_time'],
            },
        ),
    ]
