# Generated by Django 2.1.1 on 2019-12-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EwsCompose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('compose_file', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('compose_json', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ews_compose',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='EwsProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectname', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('project_json', models.CharField(blank=True, max_length=255, null=True)),
                ('repository', models.CharField(blank=True, max_length=255, null=True)),
                ('tab_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'db_table': 'ews_project',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='EwsProjectApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('app_json', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ews_project_app',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='EwsProjectVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('version_json', models.CharField(blank=True, max_length=255, null=True)),
                ('tab_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.EwsProject')),
            ],
            options={
                'db_table': 'ews_project_version',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='ewsprojectapp',
            name='tab_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.EwsProjectVersion'),
        ),
        migrations.AddField(
            model_name='ewscompose',
            name='tab_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.EwsProject'),
        ),
        migrations.AddField(
            model_name='ewscompose',
            name='tab_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.EwsProjectVersion'),
        ),
    ]
