# Generated by Django 2.1.1 on 2018-11-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ewsproject',
            name='tab_user',
        ),
        migrations.AddField(
            model_name='ewsproject',
            name='repository',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
