# Generated by Django 2.1.1 on 2018-12-13 19:02

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20181120_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='EwsCompose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('compose_file', models.FileField(max_length=255, upload_to=project.models.get_file_path)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('compose_json', models.CharField(blank=True, max_length=255, null=True)),
                ('tab_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.EwsProject')),
                ('tab_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.EwsProjectVersion')),
            ],
            options={
                'db_table': 'ews_compose',
                'ordering': ['-created_time'],
            },
        ),
    ]
